### ISSUE TITLE
Using constraint with scrollView/login onclick listener

### ISSUE THREAD

**Issue by Enobong-kingsley** [gconnect/POSAgentRecord#5]
**Is your feature request related to a problem? Please describe.**
Constraint is not properly done and as a result not fitting smaller phone sizes, and the login button is not taking the user to the landing page. In addition scrollView should be implemented.

**Describe the solution you'd like**
Fix the constraint,add a scrollView and login onClick listener.

**Describe alternatives you've considered**
Most preferably constraint the text and images to one another and not parent, change the onclick to landing page, and add scroll view. 

**Would you like to work on it?**
Yes i would like to work on it.

**Comment by gconnect** [comment]
Thanks. You can work on it.
